/**
 * Export/Import des nativen Datenverzeichnisses als tar.
 *
 * Export: alles außer `run/` — dort liegen nur Dateien, die jeder Start neu
 * schreibt (livekit.yaml, mediamtx.yml, Caddyfile, weed-s3.json, garnet.conf,
 * frpc.toml mit dem Tunnel-Token, die PID-Dateien). Geschrieben wird erst in
 * eine Nachbardatei; nur ein vollständiges Archiv ersetzt das Ziel.
 *
 * Import: NIE erst löschen, dann entpacken (ein kaputtes Archiv oder eine
 * volle Platte hätte sonst alles genommen). Stattdessen in ein Nachbar-
 * verzeichnis entpacken, prüfen, säubern, dann tauschen; der alte Stand wird
 * erst nach gelungenem Tausch gelöscht.
 *
 * Säubern heißt: aus dem Archiv stammende Postgres-Konfiguration wird nicht
 * übernommen. postgresql.conf/postgresql.auto.conf/pg_hba.conf einer
 * präparierten Sicherung könnten `archive_command`, `shared_preload_libraries`
 * oder offene Anmelderegeln mitbringen — und Postgres führt das beim nächsten
 * Start aus. `run/` und eine stehengebliebene postmaster.pid fliegen ebenfalls
 * raus (letztere ließe Postgres mit einer recycelten PID für „läuft schon“
 * halten).
 */

import { existsSync, mkdirSync, readdirSync, copyFileSync, writeFileSync } from 'node:fs';
import { rename, rm } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { join, dirname, basename } from 'node:path';
import { randomBytes } from 'node:crypto';
import { promisify } from 'node:util';

import { systemProgramm } from './laufreste.ts';

const execFileAsync = promisify(execFile);

export type TransferErgebnis = { ok: true } | { ok: false; error: string };

/** Aus dem Export ausgenommen, beim Import verworfen. */
const NICHT_SICHERN = new Set(['run']);

/** pg_hba.conf: nur TCP über Loopback, jede Verbindung mit Passwort — wie
 *  initdb mit --auth-host=scram-sha-256 (postgres.ts::ensureInitDb). Keine
 *  `local`-Zeile: alle Dienste verbinden sich per TCP, und ein Postgres-Bau
 *  ohne Unix-Sockets lehnte die ganze Datei sonst ab. */
export const PG_HBA_EIGEN = `# Von Pulse geschrieben (Import) — nur Loopback, Passwortpflicht.
host    all   all   127.0.0.1/32   scram-sha-256
host    all   all   ::1/128        scram-sha-256
`;

/** Rückfall, wenn die bestehende Installation keine postgresql.conf hat —
 *  die Laufzeitwerte setzt ohnehin postgresArgs() auf der Kommandozeile. */
export const PG_CONF_MINIMAL = `# Von Pulse geschrieben (Import). Port, Adresse und Speicher setzt der Start
# auf der Kommandozeile (postgres.ts::postgresArgs).
listen_addresses = '127.0.0.1'
datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.english'
`;

const PG_AUTO_CONF_LEER = `# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
`;

export interface TransferDeps {
  /** tar-Programm — Windows: das eigene bsdtar aus System32 (siehe systemProgramm). */
  tar: string;
}

export const standardTransferDeps = (): TransferDeps => ({ tar: systemProgramm('tar.exe') });

function fehlertext(e: unknown): string {
  const err = e as { stderr?: string; message?: string };
  return (err.stderr?.trim() || err.message || String(e)).slice(0, 600);
}

const TAR_OPTIONEN = { windowsHide: true, maxBuffer: 16 * 1024 * 1024 };

/** Verzeichnis entfernen, Fehler schlucken — nur für Aufräumen nach einem
 *  bereits gemeldeten Fehlschlag. */
async function wegraeumen(pfad: string): Promise<void> {
  await rm(pfad, { recursive: true, force: true }).catch(() => {});
}

function zufall(): string {
  return randomBytes(4).toString('hex');
}

export async function exportiereDaten(root: string, ziel: string, deps: TransferDeps = standardTransferDeps()): Promise<TransferErgebnis> {
  if (!existsSync(root)) return { ok: false, error: 'keine Daten vorhanden' };
  const eintraege = readdirSync(root).filter((e) => !NICHT_SICHERN.has(e));
  if (eintraege.length === 0) return { ok: false, error: 'keine Daten vorhanden' };
  const teil = join(dirname(ziel), `.${basename(ziel)}.${zufall()}.teil`);
  try {
    // Einträge einzeln statt `.` + --exclude: die Mustersemantik von
    // --exclude unterscheidet sich zwischen bsdtar und GNU-tar, eine Liste nicht.
    await execFileAsync(deps.tar, ['-cf', teil, '-C', root, ...eintraege], TAR_OPTIONEN);
    await rename(teil, ziel);
    return { ok: true };
  } catch (e) {
    await rm(teil, { force: true }).catch(() => {});
    return { ok: false, error: `Export fehlgeschlagen: ${fehlertext(e)}` };
  }
}

/** Entpackten Stand prüfen + säubern. bisher = bestehende Installation
 *  (Quelle der eigenen postgresql.conf), darf fehlen. */
export function saeubereImport(neu: string, bisher: string): string | null {
  const pg = join(neu, 'pg');
  if (!existsSync(join(pg, 'PG_VERSION'))) {
    return 'Das Archiv ist keine Pulse-Server-Sicherung (Datenbank fehlt).';
  }
  const eigeneConf = join(bisher, 'pg', 'postgresql.conf');
  if (existsSync(eigeneConf)) copyFileSync(eigeneConf, join(pg, 'postgresql.conf'));
  else writeFileSync(join(pg, 'postgresql.conf'), PG_CONF_MINIMAL, 'utf8');
  writeFileSync(join(pg, 'postgresql.auto.conf'), PG_AUTO_CONF_LEER, 'utf8');
  writeFileSync(join(pg, 'pg_hba.conf'), PG_HBA_EIGEN, 'utf8');
  return null;
}

async function entferneVerworfenes(neu: string): Promise<void> {
  for (const e of NICHT_SICHERN) await rm(join(neu, e), { recursive: true, force: true });
  await rm(join(neu, 'pg', 'postmaster.pid'), { force: true });
  await rm(join(neu, 'pg', 'postmaster.opts'), { force: true });
}

export async function importiereDaten(root: string, archiv: string, deps: TransferDeps = standardTransferDeps()): Promise<TransferErgebnis> {
  if (!existsSync(archiv)) return { ok: false, error: 'Archiv nicht gefunden' };
  const neu = `${root}.import-${zufall()}`;
  const alt = `${root}.alt-${zufall()}`;
  try {
    mkdirSync(neu, { recursive: true });
    // bsdtar wie GNU-tar: ohne -P keine absoluten Pfade und kein `..` —
    // das Archiv kann nicht aus `neu` herausschreiben.
    await execFileAsync(deps.tar, ['-xf', archiv, '-C', neu], TAR_OPTIONEN);
    await entferneVerworfenes(neu);
    const problem = saeubereImport(neu, root);
    if (problem) {
      await rm(neu, { recursive: true, force: true });
      return { ok: false, error: problem };
    }
  } catch (e) {
    await wegraeumen(neu);
    return { ok: false, error: `Import fehlgeschlagen: ${fehlertext(e)}` };
  }

  const hatteAlt = existsSync(root);
  try {
    if (hatteAlt) await rename(root, alt);
  } catch (e) {
    await wegraeumen(neu);
    return { ok: false, error: `Bisherige Daten lassen sich nicht beiseitelegen (noch in Benutzung?): ${fehlertext(e)}` };
  }
  try {
    await rename(neu, root);
  } catch (e) {
    if (hatteAlt) await rename(alt, root).catch(() => {});
    await wegraeumen(neu);
    return { ok: false, error: `Import fehlgeschlagen, bisherige Daten bleiben: ${fehlertext(e)}` };
  }
  // Ab hier ist der Import gelungen; ein Rest von `alt` kostet nur Platz.
  if (hatteAlt) await wegraeumen(alt);
  return { ok: true };
}
