#!/bin/sh
# coturn — generate static-auth-secret + render config from template.
# Opt-out: PULSE_TURN_DISABLED=true → touch turn.disabled flag, the longrun
# unit will sleep instead of starting turnserver.
set -eu
DATA="${PULSE_DATA_PATH:-/data}"
COTURN_DATA="${DATA}/coturn"
mkdir -p "${COTURN_DATA}"
chown pulse:pulse "${COTURN_DATA}"

if [ "${PULSE_TURN_DISABLED:-false}" = "true" ]; then
    echo "[04-init-coturn] PULSE_TURN_DISABLED=true — skipping coturn setup"
    touch /var/run/pulse/turn.disabled
    chown pulse:pulse /var/run/pulse/turn.disabled
    exit 0
fi
rm -f /var/run/pulse/turn.disabled || true

# Secret persists across container restarts → active sessions survive.
# Manual rotation: delete /data/coturn/secret + restart container.
if [ ! -f "${COTURN_DATA}/secret" ]; then
    python3 -c 'import secrets; print(secrets.token_hex(32))' > "${COTURN_DATA}/secret"
    chmod 0600 "${COTURN_DATA}/secret"
    chown pulse:pulse "${COTURN_DATA}/secret"
    echo "[04-init-coturn] generated new coturn shared secret"
fi
COTURN_SECRET=$(cat "${COTURN_DATA}/secret")

# Hostname is required for the realm.
HOSTNAME="${PULSE_HOSTNAME:?PULSE_HOSTNAME required}"

# external-ip: ohne sie relayt coturn hinter Docker/NAT auf die interne Bridge-IP
# und ist für externe Clients unbrauchbar (F13). PULSE_PUBLIC_IP wenn gesetzt,
# sonst per HTTP-Lookup ermitteln (best effort, schlägt offline einfach fehl).
PUBLIC_IP="${PULSE_PUBLIC_IP:-}"
if [ -z "$PUBLIC_IP" ]; then
    PUBLIC_IP=$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)
fi
EXTERNAL_IP_LINE=""
if [ -n "$PUBLIC_IP" ]; then
    EXTERNAL_IP_LINE="external-ip=${PUBLIC_IP}"
    echo "[04-init-coturn] external-ip=${PUBLIC_IP}"
else
    echo "[04-init-coturn] WARN: could not determine a public IP — set PULSE_PUBLIC_IP," \
         "otherwise the TURN relay is useless behind NAT."
fi

cat > /etc/coturn/turnserver.conf <<EOF
# Auto-generated by infra/self-host cont-init at $(date -u +%FT%TZ).
# Manual edits will be overwritten on next container start.

listening-port=3478
${EXTERNAL_IP_LINE}
fingerprint
use-auth-secret
static-auth-secret=${COTURN_SECRET}
realm=${HOSTNAME}

# Default pid/db paths are root-owned (/var/run/turnserver.pid,
# /var/lib/turn/turndb) — redirect to pulse-writable spots so the
# unprivileged process can actually start.
pidfile=/var/run/pulse/turnserver.pid
userdb=${COTURN_DATA}/turndb

# Bind to all interfaces — Docker port-publishing handles exposure.
# Restrict relay-IPs to known address (see PULSE_PUBLIC_IP override below).
no-cli
no-tls
no-dtls

# voice-signaling reads /data/coturn/secret directly and mints time-limited
# REST-API credentials (HMAC-SHA1 over username), so coturn validates them
# against this same static-auth-secret.

# Don't relay to private ranges — defense in depth against SSRF via TURN.
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255

# Logs to stderr → s6 → Docker
log-file=stdout
no-stdout-log
simple-log
EOF
chmod 0644 /etc/coturn/turnserver.conf

echo "[04-init-coturn] /etc/coturn/turnserver.conf rendered (realm=${HOSTNAME})"
