#!/bin/sh
# Compose /etc/pulse/env.sh — sourced by every longrun service. Holds the
# runtime env: DB URL, Redis URL, JWT key paths, internal secret. Anything
# that depends on a generated secret lands here.
set -eu
DATA="${PULSE_DATA_PATH:-/data}"
KEYS="${DATA}/jwt_keys"
mkdir -p /etc/pulse
chown pulse:pulse /etc/pulse

# PULSE_CLOUD_ORIGIN ist im Dockerfile-ENV defaultiert auf
# https://howispulse.com — aber ein Operator könnte es explizit
# auf "" setzen (z.B. Air-Gap-Deploy). In dem Fall absorbieren wir den
# Default lokal, damit CORS_ALLOW_ORIGINS unten kein führendes Komma erbt.
: "${PULSE_CLOUD_ORIGIN:=https://howispulse.com}"

PG_PASS=$(cat "${KEYS}/postgres.password")
INTERNAL_SECRET=$(cat "${KEYS}/internal_service.token")
CERT_CHALLENGE=$(cat "${KEYS}/cert_challenge.secret")
LIVEKIT_KEY=$(cat "${KEYS}/livekit.key")
LIVEKIT_SECRET=$(cat "${KEYS}/livekit.secret")

cat > /etc/pulse/env.sh <<EOF
# Generated by infra/self-host/scripts/07-render-env.sh at $(date -u +%FT%TZ).
# DO NOT EDIT — rerun the container to regenerate.

# Postgres (local socket, no TLS — we're in the same process tree)
export POSTGRES_USER=pulse
export POSTGRES_PASSWORD='${PG_PASS}'
export POSTGRES_DB=dcc
export POSTGRES_HOST=127.0.0.1
export POSTGRES_PORT=5432
export DATABASE_URL='postgresql+asyncpg://pulse:${PG_PASS}@127.0.0.1:5432/dcc'

# Redis (local-only bind, no auth — single-container threat model)
export REDIS_URL='redis://127.0.0.1:6379/0'

# JWT (RS256 chat-gateway issuer)
export JWT_PRIVATE_KEY_FILE='${KEYS}/jwt_private.pem'
export JWT_PUBLIC_KEY_FILE='${KEYS}/jwt_public.pem'
export JWT_ISSUER='https://${PULSE_HOSTNAME}'
export JWT_AUDIENCE=pulse-self-host
export JWT_ACCESS_TTL_SECONDS=900
export JWT_REFRESH_TTL_SECONDS=2592000

# Self-Host session-token signing (Ed25519 — for /cert-login session tokens).
# The chat-gateway reads SESSION_SIGNING_KEY_FILE (settings.session_signing_key_file);
# its default is the RELATIVE "./data/jwt_keys/session_signing.pem", which under
# s6 (cwd=/opt/pulse/services/chat-gateway) is non-writable → cert-login/verify
# crashes with PermissionError and the browser only sees a masked CORS error.
# The key is lazily generated + persisted on first cert-login, so it MUST point
# at the writable /data volume. (PULSE_SESSION_TOKEN_* were the wrong names — no
# code reads them.)
export SESSION_SIGNING_KEY_FILE='${KEYS}/session_signing.pem'

# Internal cross-service auth
export INTERNAL_SERVICE_SECRET='${INTERNAL_SECRET}'
export CHAT_GATEWAY_URL='http://127.0.0.1:8002'
export MEDIA_SVC_URL='http://127.0.0.1:8004'
export AUTH_JWKS_URL='http://127.0.0.1:8001/.well-known/jwks.json'

# Cert-login challenge HMAC
export CHAT_GATEWAY_CHALLENGE_SECRET='${CERT_CHALLENGE}'

# LiveKit (voice-signaling mints tokens with these; livekit-server validates)
export LIVEKIT_API_KEY='${LIVEKIT_KEY}'
export LIVEKIT_API_SECRET='${LIVEKIT_SECRET}'
export LIVEKIT_URL='ws://127.0.0.1:7880'

# MediaMTX API (media-svc polls it)
export MEDIAMTX_API_URL='http://127.0.0.1:9997/v3/paths/list'

# CORS — Cloud-Foundation needs to embed self-host endpoints
export CORS_ALLOW_ORIGINS='${PULSE_CLOUD_ORIGIN},https://${PULSE_HOSTNAME}'

# WebAuthn (rpId = hostname; passkeys created here will only validate on it)
export WEBAUTHN_RP_ID='${PULSE_HOSTNAME}'
export WEBAUTHN_ORIGIN='https://${PULSE_HOSTNAME}'

# Snowflake worker IDs (single-container — fixed)
export SNOWFLAKE_WORKER_ID_AUTH=1
export SNOWFLAKE_WORKER_ID_CHAT=2
export SNOWFLAKE_WORKER_ID_VOICE=3

# Self-host identity.
export PULSE_HOSTNAME='${PULSE_HOSTNAME}'
export PULSE_INSTANCE_MODE=self-host
# PULSE_INSTANCE_ID = the Snowflake-ID the Cloud assigned at approval. Without it
# chat-gateway hard-fails on startup (app.py — pulse_instance_id==0 +
# mode=self-host → RuntimeError). The longrun services source ONLY this env.sh,
# so the docker-run -e value MUST be rendered through here — handing it to the
# container env alone never reaches the services.
export PULSE_INSTANCE_ID='${PULSE_INSTANCE_ID}'
export PULSE_INSTANCE_OWNER_ID='${PULSE_INSTANCE_OWNER_ID}'
export PULSE_CLOUD_ORIGIN='${PULSE_CLOUD_ORIGIN}'
export PULSE_ADMIN_EMAIL='${PULSE_ADMIN_EMAIL}'
# Cloud-pairing credentials (reserved for the Phase 4–6 instance↔Cloud
# handshake — heartbeat / suspend-enforcement). Rendered so they're ready;
# no service consumes them yet.
export PULSE_CLOUD_CLIENT_ID='${PULSE_CLOUD_CLIENT_ID}'
export PULSE_CLOUD_CLIENT_SECRET='${PULSE_CLOUD_CLIENT_SECRET}'

# Logging
export PULSE_LOG_LEVEL='${PULSE_LOG_LEVEL:-info}'

# VAPID keys for Web-Push (chat-gateway). Defaults are a relative path,
# which resolves to the wrong dir under s6-supervised processes (cwd=/).
# Force an absolute, pulse-owned location inside /data/jwt_keys.
export VAPID_KEY_FILE='${KEYS}/vapid.json'
EOF

chmod 0640 /etc/pulse/env.sh
chown root:pulse /etc/pulse/env.sh

echo "[07-render-env] /etc/pulse/env.sh rendered"
